### ISSUE TITLE
disk script

### ISSUE THREAD

**Issue by yanboyang713** [gsanhueza/ArchISOMaker#11]
Hello @gsanhueza ,

Good day to you.

I found there is a **Script** for full disk encryption and format.
https://gist.github.com/kurtmc/ae586ef83b6ea05635bf310f1160d138

Do you think it is good to merge in?

Boyang

**Comment by gsanhueza** [comment]
I haven't tested the script yet, but it would be an interesting addition.
Nonetheless, the current implementation of the script seems to be too hardcoded, compared to what I designed for my repository.

Maybe extract relevant code into some functions that can be added to the [installation scripts](https://github.com/gsanhueza/ArchScripts)?

**Comment by yanboyang713** [comment]
yes, I think so. Just extract disk format relevant.

**Comment by yanboyang713** [comment]
Hello @gsanhueza,

I tested below disk format and mount script. works good
https://github.com/yanboyang713/ArchScripts/blob/0851ebefd438421872a410c271ea98600dfc2f30/disk.sh

Boyang Y
