### ISSUE TITLE
Cloud-init

### ISSUE THREAD

**Issue by yanboyang713** [gsanhueza/ArchISOMaker#12]
Hello @gsanhueza,

I also think we could add [Cloud-init](https://wiki.archlinux.org/title/Cloud-init), let image could work with cloud.

I have not test yet. I used [Proxmox](https://pve.proxmox.com/wiki/Main_Page) as my edge cloud.

**Comment by gsanhueza** [comment]
Implementing this idea falls out of scope of my project, as the purpose of this repository is to create an ISO file that can be used without internet access.

As the [link](https://wiki.archlinux.org/title/Cloud-init) that you sent says:

"It is needed in Arch Linux images that are built with the intention of being launched in cloud environments like [OpenStack](https://wiki.archlinux.org/title/OpenStack), [AWS](https://wiki.archlinux.org/title/AWS) etc."

That means if you want to use the ISO generated with this project in a cloud environment that has to have internet, you might be better served by using the default ISO, or forking this repository to implement cloud-based images that fit better your scope.

Although I think you can use my ArchScripts repository to simplify installation of the ISO file.

**Comment by yanboyang713** [comment]
yes, I am looking your ArchScripts one by one
