### ISSUE TITLE
i got this error while building an iso

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [gsanhueza/ArchISOMaker#15]
```
>>> xorg-server has now the ability to run without root rights with
    the help of systemd-logind. xserver will fail to run if not launched
    from the same virtual terminal as was used to log in.
    Without root rights, log files will be in ~/.local/share/xorg/ directory.

    Old behavior can be restored through Xorg.wrap config file.
    See Xorg.wrap man page (man xorg.wrap).
error: could not commit transaction
error: failed to commit transaction (transaction aborted)
Errors occurred, no packages were upgraded.
==> ERROR: Failed to install packages to new root
```

**Comment by GuestSneezeOSDev** [comment]
i tried adding and removing repositories

**Comment by gsanhueza** [comment]
@GuestSneezeOSDev The output mentioned above seems insufficient to determine the reason for the failure, as it doesn't seem to be a Xorg error.

Which steps did you take after cloning this repository?
Do you have the full output?

**Comment by GuestSneezeOSDev** [comment]
no i do not have the full out put but after every package installed i got this output
```
warning: directory permissions differ on /home/xaruc/AOS/working/x86_64/airootfs/usr/
filesystem: 777  package: 755
```

**Comment by GuestSneezeOSDev** [comment]
i did rebuild it and i got the same error

**Comment by gsanhueza** [comment]
GIven that your filesystem's permissions are 777 (when normally it's 755), are you building the ISO on an NTFS partition, or in a non-standard partition?

**Comment by GuestSneezeOSDev** [comment]
Yes i am building it on an NTFS partition

**Comment by gsanhueza** [comment]
Then that's your issue. NTFS partitions do not handle symlinks correctly, as required by some packages.
If you're using an NTFS partition, then it's very probably you're on Windows.

I'd recommend you to use a virtual machine with ArchLinux installed (yeah, it sounds redundant, like installing ArchLinux on a VM to build an ISO that allow you to install ArchLinux).

Alternatively, I've just tested that you can also use WSL to build the ISO, by selecting a distro, like [this one](https://apps.microsoft.com/detail/9mznmnksm73x).

**Comment by GuestSneezeOSDev** [comment]
Thank You So much,I was using arch wsl but on my c drive and i did not that was the issue
