### ISSUE TITLE
OS-RELEASE ERROR

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [gsanhueza/ArchISOMaker#16]
```
error: failed to commit transaction (conflicting files)
filesystem: /root/GSOS/work/x86_64/airootfs/usr/lib/os-release exists in filesystem
Errors occurred, no packages were upgraded.
==> ERROR: Failed to install packages to new root
```

**Comment by gsanhueza** [comment]
Although I haven't seen that error before, I'd recommend you to delete the `work` and `TEMPMNT` directories, and try again.

If the error persists, report back with a more complete output, so I can try to reproduce it (for example, using `pwd` to show your current location, and `ls -l` to show all files).

**Comment by GuestSneezeOSDev** [comment]
ok i will try again

**Comment by gsanhueza** [comment]
As there is no response anymore, I'll assume you fixed your problem and close the issue.
