### ISSUE TITLE
Add PKGBUILD support and automatic GUI

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [gsanhueza/ArchISOMaker#17]
i want to implement some aur packages in my Archiso

**Comment by gsanhueza** [comment]
That's cool. I'd recommend researching it in the Arch wiki so you can add it to your personal implementation.

**Comment by GuestSneezeOSDev** [comment]
ty i heard you can make a repository with pkgbuilds but mi

**Comment by GuestSneezeOSDev** [comment]
i already use the project in my OS https://github.com/GuestSneezeOS/GuestSneezeOS so i can probably make GUI work

**Comment by gsanhueza** [comment]
You can make GUI work by checking how to make your custom repository.
Still, you have to check whether your PKGBUILD projects are part of the ISO, or part of the installable packages (or both).
The Arch wiki has more information for that.
