### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by tuxarch** [gsanhueza/ArchISOMaker#7]
> error: target not found: wpa_actiond
> ==> ERROR: Failed to install packages to new root
![screenshot](https://user-images.githubusercontent.com/17531010/55572431-3615c380-5710-11e9-8d40-a96099373d8f.png)

**Comment by gsanhueza** [comment]
Thanks for reporting it! 
This issue has been solved by deleting wpa_actiond from the ISO packages, as it's unneeded (the ISO still works).
